
    #補完機能

    #python補完機能
    [[plugins]]
    repo='zchee/deoplete-jedi'
    #insertモードで読み込み
    on_i=1
    #指定したファイルタイプの時読み込む
    on_ft=['python']
    depends=['deoplete.nvim']
    hook_post_source='''
    g:deoplete#source#jedi#server_timeout=40
    '''

    #c++補完機能
    [[plugins]]
    repo='tweekmonster/deoplete-clang2'
    hook_post_source='''
    set runtimepath+=/tmp/deoplete.nvim/
    set runtimepath+=~/tmp/deoplete-clang/
    let g:deoplete#enable_at_startup=1
    let g:deoplete#sources#clang#executable='/usr/bin/clang'
    '''
    on_ft=['c','cpp','cmake']
    on_i=1
    depends=['deoplete.nvim']

    #java補完機能
    [[plugins]]
    repo='artur-shaik/vim-javacomplete2'
    hook_post_source='''
    nnoremap <F4> <Plug>(JavaComplete-Imports-AddSmart)
    inoremap <F4> <Plug>(JavaComplete-Imports-AddSmart)
    nnoremap <F7> <Plug>(JavaComplete-Imports-RemoveUnused)
    inoremap <F7> <Plug>(JavaComplete-Imports-RemoveUnused)
    '''
    on_ft=['java']
    depends=['deoplete.nvim']

    #javascript補完機能
    repo='carlitux/deoplete-ternjs'
    on_ft=['javascript']
    on_i=1
    depends=['deoplete.nvim']

    #html補完
    [[plugins]]
    repo='mattn/emmet-vim'
    hook_post_source='''
    let g:user_emmet_settings={
        \ 'lang' : 'ja',
        \ 'html' : {
        \   'filters' : 'html',
        \ },
        \ 'css' : {
        \   'filters' : 'fc',
        \ },
        \ 'php' : {
        \   'extends' : 'html',
        \   'filters' : 'html',
        \ },
        \ }
       '''
    on_ft=['html']
    on_i=1

    #html
    [[plugins]]
    repo='tpope/vim-surround'
    on_ft=['html']

    [[plugins]]
    repo='othree/html5.vim'
    on_ft=['html']
    on_i=1

    #neosnippet
    [[plugins]]
    repo='Shougo/neosnippet'
    hook_source='''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
    if has('conceal')
        set conceallevel=2 concealcursor=niv
    endif
    '''
    on_i=1
    on_ft=['snippet']
    depends=['neosnippet-snippets']

    #neco-vim
    [[plugins]]
    repo='Shougo/neco-vim'
    on_i=1
    on_ft=['vim']
    depends=['deoplete.nvim']


    #自動括弧
    [[plugins]]
    repo='cohama/lexima.vim'
    on_i=1

    #html-scriptインデント
    [[plugins]]
    repo='osyo-manga/vim-precious'
    on_ft=['html', 'toml']

    [[plugins]]
    repo='kana/vim-smartchr'
    hook_add='''
    inoremap <expr> , smartchr#loop(', ',',')
    autocmd Filetype python,pyrex,c,cpp,lua inoremap <expr> < smartchr#loop(' < ', ' <= ', '<', ' << ')
    autocmd Filetype python,pyrex,c,cpp,lua inoremap <expr> > smartchr#loop(' > ', ' >= ', '>', ' >> ')

    autocmd Filetype python,pyrex,lua inoremap <expr> = smartchr#one_of(' = ',' == ','=')
    autocmd FileType python,pyrex,lua inoremap <expr> + smartchr#one_of(' + ', '+')
    autocmd FileType python,pyrex,lua inoremap <expr> - smartchr#one_of(' - ', '-')
    autocmd FileType python,pyrex,lua inoremap <expr> / smartchr#one_of(' / ', ' // ', '/')
    autocmd FileType python,pyrex inoremap <expr> * smartchr#one_of(' * ', ' ** ', '*')
    autocmd FileType python,pyrex inoremap <expr> & smartchr#one_of(' & ', ' && ', '&')

    autocmd FileType lua inoremap <expr> ^ smartchr#loop(' ^ ', '^')

    autocmd FileType c,cpp inoremap <expr> + smartchr#one_of(' + ', '++', ' += ', '+')
    autocmd FileType c,cpp inoremap <expr> - smartchr#one_of(' - ', '--', ' -= ', '-')
    autocmd FileType c,cpp inoremap <expr> & smartchr#one_of('&', ' && ', ' & ', '&=')
    " autocmd FileType c,cpp inoremap <expr> | smartchr#one_of(' | ', ' || ', ' |= ', '|')
    autocmd FileType c,cpp inoremap <expr> % smartchr#one_of(' % ', '%', '%=')

    autocmd Filetype c,cpp inoremap <expr> . smartchr#one_of('.','->')
    '''
    on_i=1

    [[plugins]]
    repo='Galooshi/vim-import-js'
    on_ft=['javascript']

    # verilog補完
    [[plugins]]
    repo='tsubota-kouga/deoplete-verilog'
    on_ft=['verilog']
    on_i=1
    depends=['deoplete.nvim']

    # lua補完
    [[plugins]]
    repo='tsubota-kouga/deoplete-lua'
    on_ft=['lua']
    on_i=1
    depends=['deoplete.nvim']

    [[plugins]]
    repo='zchee/deoplete-zsh'
    on_ft=['zsh']
    on_i=1
    depends=['deoplete.nvim']
