
    #dein
    [[plugins]]
    repo='Shougo/dein.vim'

    [[plugins]]
    repo='Shougo/deoplete.nvim'
    hook_add='''
    let g:deoplete#enable_at_startup=1
    let g:deoplete#omni_patterns={}
    let g:deoplete#auto_complete_delay=0
    let g:deoplete#auto_complete_start_length=1
    imap <expr><tab> pumvisible() ? "\<c-n>" :
    \neosnippet#expandable_or_jumpable() ?
    \ "\<plug>(neosnippet_expand_or_jump)" : "\<tab>"
    '''

    [[plugins]]
    repo='Shougo/vimproc.vim'
    hook_post_update  =  '''
        if dein#util#_is_windows()
            let cmd  =  tools\\update-dll-mingw'
        elseif dein#util#_is_cygwin()
            let cmd  =  'make -f make_cygwin.mak'
        elseif executable('gmake')
            let cmd  =  'gmake'
        else
            let cmd  =  'make'
        endif
        let g:dein#plugin.build  =  cmd
                                        '''
    #簡単実行できる
    [[plugins]]
    repo='thinca/vim-quickrun'
    hook_post_update='''
        if !(exists("g:quickrun_config")
            let g:quickrun_config={}
        endif
        let g:quickrun_config["watchdogs_checker/_"]={
            \"outputter/quickfix/open_cmd" : "",
        \}
        let g:quickrun_config={'*':{'hook/time/enable':'1'},}
        '''
    [[plugins]]
    repo='osyo-manga/shabadou.vim'

    #構文チェックプラグイン
    # [[plugins]]
    # repo='osyo-manga/vim-watchdogs'


    #簡単にコメントアウトできる
    [[plugins]]
    repo='tomtom/tcomment_vim'
    hook_add='''
    '''

    #コマンド集
    [[plugins]]
    repo='Shougo/denite.nvim'

    #
    [[plugins]]
    repo='LeafCage/yankround.vim'
    hook_add='''
                nmap p <Plug>(yankround-p)
                xmap p <Plug>(yankround-p)
                nmap P <Plug>(yankround-P)
                nmap gp <Plug>(yankround-gp)
                xmap gp <Plug>(yankround-gp)
                nmap gP <Plug>(yankround-gP)
                nmap <C-p> <Plug>(yankround-prev)
                nmap <C-n> <Plug>(yankround-next)
                '''

    #画面背景を黒にする
    [[plugins]]
    repo='nanotech/jellybeans.vim'

    #文字に色をつける
    [[plugins]]
    repo='tomasr/molokai'
    hook_add='''
    if dein#tap('molokai')
        colorscheme molokai
    endif
    set background=dark
    set termguicolors
    set t_Co=256
    syntax enable
    filetype plugin indent on
    "neovimに入った時に読み込む
    au MyAutoCmd VimEnter * nested colorscheme molokai
    '''

    #ステータスラインの表示内容強化
    [[plugins]]
    repo='itchyny/lightline.vim'

    #末尾の全角と半角の空白を色付け :FixWhitespace
    [[plugins]]
    repo='bronson/vim-trailing-whitespace'

    #インデントの可視化
    [[plugins]]
    repo='Yggdroot/indentLine'

    #tomlファイルの構文予測
    [[plugins]]
    repo='cespare/vim-toml'
    on_ft='toml'

    #ファイルをツリー構造で表示可能
    [[plugins]]
    repo='scrooloose/nerdtree'
    hook_source='''
    let g:syntastic_vim_checkers=['vint']
    '''

    # #文法チェック
    # [[plugins]]
    # repo='w0rp/ale'
    # hook_add='''
    # let g:ale_fix_on_save=1
    # let g:ale_lint_on_text_changed='never'
    # let g:ale_set_loclist=0
    # let g:ale_set_quickfix=1
    # let g:ale_completion_enabled=1
    # nmap <silent> <C-k> <Plug>(ale_previous_wrap)
    # nmap <silent> <C-j> <Plug>(ale_next_wrap)
    # '''

    # repo='vim-syntastic/syntastic'
    # hook_add='''
    # set statusline+=%#warningmsg#
    # set statusline+=%{SyntasticStatuslineFlag()}
    # set statusline+=%*
    # let g:syntastic_always_populate_loc_list = 1
    # let g:syntastic_auto_loc_list = 1
    # let g:syntastic_check_on_open = 1
    # let g:syntastic_check_on_wq = 0
    # '''

    #snippets
    [[plugins]]
    repo='Shougo/neosnippet-snippets'

    #filetype
    [[plugins]]
    repo='Shougo/context_filetype.vim'

    # 1回出てきたものをハイライト
    [[plugins]]
    repo='osyo-manga/vim-brightest'

    #<F2>でヘッダとソースを行き来
    [[plugins]]
    repo='kana/vim-altr'
    hook_source='''
    nmap <F2> <Plug>(altr-forward)
    '''
    # #vimshell
    # [[plugins]]
    # repo='Shougo/vimshell'
